Controllers/CRUDController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_497.Models;

namespace Project_497.Controllers
{
    public class CRUDController : Controller
    {
        private projectEntities3 db = new projectEntities3();

        // GET: CRUD
        public ActionResult Index()
        {
            var products = db.products.Include(p => p.Admin).Include(p => p.category).Include(p => p.SubCategoryID1);
            return View(products.ToList());
        }

        // GET: CRUD/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: CRUD/Create
        public ActionResult Create()
        {
            ViewBag.userId = new SelectList(db.Admins, "userId", "userName");
            ViewBag.categoryId = new SelectList(db.categories, "categoryId", "name");
            
            ViewBag.SubCategoryID = new SelectList(db.SubCategoryIDs, "SubCategoryID1", "name");
            return View();
        }

        // POST: CRUD/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create( product product)
        {
            if (ModelState.IsValid)
            {
                product.click = 0;
                product.sellStartDate = DateTime.Now;
                product.clickDate = DateTime.Now.Date;
                product.sellEndDate = null;
                product.January = 0;
                product.February = 0;
                product.March = 0;
                product.April = 0;
                product.May = 0;
                product.June = 0;
                product.July = 0;
                product.August = 0;
                product.September = 0;
                product.October = 0;
                product.November = 0;
                product.December = 0;
                product.predection = 0;
                product.previous_click = 0;
                product.count_improvment = 0;
                db.products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.userId = new SelectList(db.Admins, "userId", "userName", product.userId);
            ViewBag.categoryId = new SelectList(db.categories, "categoryId", "name", product.categoryId);
           
            ViewBag.SubCategoryID = new SelectList(db.SubCategoryIDs, "SubCategoryID1", "name", product.SubCategoryID);
            return View(product);
        }

        // GET: CRUD/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.userId = new SelectList(db.Admins, "userId", "userName", product.userId);
            ViewBag.categoryId = new SelectList(db.categories, "categoryId", "name", product.categoryId);
          
            ViewBag.SubCategoryID = new SelectList(db.SubCategoryIDs, "SubCategoryID1", "name", product.SubCategoryID);
            return View(product);
        }

        // POST: CRUD/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(product product)
        {
            if (ModelState.IsValid)
            {
               
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.userId = new SelectList(db.Admins, "userId", "userName", product.userId);
            ViewBag.categoryId = new SelectList(db.categories, "categoryId", "name", product.categoryId);
           
            ViewBag.SubCategoryID = new SelectList(db.SubCategoryIDs, "SubCategoryID1", "name", product.SubCategoryID);
            return View(product);
        }

        // GET: CRUD/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: CRUD/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project_497.Models;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace Project_new.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        projectEntities3 db = new projectEntities3();
        [HttpPost]
        public ActionResult LoginAuthentication(Admin id)
        {
            var UserDetails = db.Admins.Where(x => x.userName == id.userName && x.password == id.password).FirstOrDefault();
            if (UserDetails == null)
            {

                id.LoginErrorMessage = "User Name or Password is not valid";
                return View("Index", id);
            }
            else
            {
                Session["userId"] = id.userId;
                Session["userName"] = id.userName;
                return RedirectToAction("Index", "Admin");
            }


        }
        public ActionResult Logout()
        {
            int userId = (int)Session["userId"];
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }


    }
}                //var Status = db.Database.ExecuteSqlCommand("INSERT INTO [ Product_Sell](productId,productName,image,sellEndDate,price) VALUES({0},{1},{2},{3},{4})", r.productId = q.productId, r.productName = q.productName, r.image = q.image, r.sellEndDate, r.price = 10000);

Views/Admin/Index.cshtml
@model Project_497.Models.Percentage
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/LayoutPage.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
    
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vertical Nav thingy</title>
    <script>
    $('.message a').click(function(){
    $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
    });
    </script>
    
    <link href="~/Content/css/adminstyle.css" rel="stylesheet" />
</head>
<body>
    <div>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
        <div id="message" align="center" class="container-fluid "style="color:black;font-size:30px;font-weight:700"> <strong>Admin Panel</strong></div>

        <div id="page-wrap" align="center">
            <div id="all">
                <ul>
                    <li style="float: right;">@Html.ActionLink("Logout", "Logout", "Login"@*, new { area = "" }, new { @class = "navbar-brand text-danger" }*@)</li>
                    <li style="float: right;">@Html.ActionLink("Admin Registration", "Create", "Registration"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>

                </ul>
                <ul>
                    <li>@Html.ActionLink("Add Sub Category", "Index", "SubCategorys"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>
                    <li>@Html.ActionLink("Add New Category", "Index", "CategoryCreateUpdateDelete"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>
                    <li>@Html.ActionLink("Add New Product", "Index", "CRUD"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>
                    <li>@Html.ActionLink("Product Boost Up", "Index", "Percentages"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>
                    <li>@Html.ActionLink("Monitor Product Reach", "Improve", "Product"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>
                </ul>
                <ul>
                    <li>@Html.ActionLink("Sell In The Month", "Need", "Product"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>
                    <li>@Html.ActionLink("Daily Sell Update", "DailySell", "productsDetails"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>
                    <li>@Html.ActionLink("Purchase suggestion", "PurchaseSuggestionForAdmin", "productsDetails"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>
                    <li>@Html.ActionLink("Predection", "predections", "productsDetails"@*, new { area = "" }, new { @class = "navbar-brand" }*@)</li>
                    <li>@Html.ActionLink("Customer Feedback", "Index", "feed_back")</li>
                </ul>

            </div>
        </div>
        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
     
        <div style="padding:380px">

        </div>
    </div>
</body>

</html>


















































@*<h2>Admin</h2>

<div class="container">
    <ul class="nav navbar-nav navbar-static-top ">
      
        <li>@Html.ActionLink("Add Sub Category", "Index", "SubCategorys", new { area = "" }, new { @class = "navbar-brand" })</li>
        <li>@Html.ActionLink("Add New Category", "Index", "CategoryCreateUpdateDelete", new { area = "" }, new { @class = "navbar-brand" })</li>
        <li>@Html.ActionLink("Add New Product", "Index", "CRUD", new { area = "" }, new { @class = "navbar-brand" })</li>
        <li>@Html.ActionLink("Add Noise", "Index", "Percentages", new { area = "" }, new { @class = "navbar-brand" })</li>
        <li>@Html.ActionLink("Monitor Product Reach", "Improve", "Product", new { area = "" }, new { @class = "navbar-brand" })</li>
        <li>@Html.ActionLink("Sell In The Month", "Need", "Product", new { area = "" }, new { @class = "navbar-brand" })</li>
        <li>@Html.ActionLink("Daily Sell Update", "DailySell", "productsDetails", new { area = "" }, new { @class = "navbar-brand" })</li>
        <li>@Html.ActionLink("Purchase suggestion", "PurchaseSuggestionForAdmin", "productsDetails", new { area = "" }, new { @class = "navbar-brand" })</li>
        <li>@Html.ActionLink("Predection", "predections", "productsDetails", new { area = "" }, new { @class = "navbar-brand" })</li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li>  @Html.ActionLink("Logout", "Logout", "Login", new { area = "" }, new { @class = "navbar-brand text-danger" })</li>


        <li>@Html.ActionLink("Admin Registration", "Create", "Registration", new { area = "" }, new { @class = "navbar-brand" })</li>


    </ul>
    
</div>*@
@*<div><p>User Name:@Session["userName"].ToString()</P></div>*@
@*<div>

    @using (Html.BeginForm("Edit", " Product"))
    {
      @Html.AntiForgeryToken()

      <div class="form-horizontal">
          <h4>Percentage</h4>
          <hr />
          @Html.ValidationSummary(true, "", new { @class = "text-danger" })
          @Html.EditorFor(model => model.percentage1)

          <div class="form-group">
              <div class="col-md-offset-2 col-md-10">
                  <input type="submit" value="Save" class="btn btn-default" />
              </div>
          </div>
      </div>
    }
    </div>*@