Controllers/productsDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_497.Models;
using System.Globalization;
using PagedList;

namespace Project_new.Controllers
{
    public class productsDetailsController : Controller
    {
        private projectEntities3 db = new projectEntities3();
       



        // GET: productsDetails
        public ActionResult Index()
        {
            return View();
        }

        //------UPDATE THE CLICK OF A SPESIFIC PRODUCT----------

        public ActionResult Details(int? id)
        {
            product p = null;

            if (id != null)
           
            {
                p = db.products.Find(id);
                if (p == null)
                {
                    return HttpNotFound();
                }
                var count_status = db.Database.ExecuteSqlCommand("UPDATE [product] SET click = {0} WHERE productId={1}", p.click + 1, p.productId);
                var click_status = db.Database.ExecuteSqlCommand("UPDATE [product] SET clickDate = {0} WHERE productId={1}",p.clickDate=DateTime.Now.Date, p.productId);// lagbe na
                db.SaveChanges();
            }

            return View(p);

        }
        //------IN EVERY MONTH HOW MANY TIME A SPECIFIC PRODUCT HAS BEEN SEEL--------

        public ActionResult BuyProduct(int? id)
        {
            product q = null;
            Product_Sell r = new Product_Sell();
            q = db.products.Find(id);
           
            
            if (id != null)
            {

                if (q == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    if (q.Buy > 0)   // buy use korchi koita product ase er jonno
                    {
                        var Buy_status = db.Database.ExecuteSqlCommand("UPDATE [product] SET Buy = {0}, count = {1},sellEndDate={2} WHERE productId={3}", q.Buy - 1, q.count + 1, q.sellEndDate = DateTime.Now, q.productId);
                        r.productId = q.productId;
                        r.productName = q.productName;
                        r.image = q.image;
                        r.sellEndDate = DateTime.Now;
                        r.price = q.price;
                        var pr =( (q.count * 100 )/ q.click );//ekhane count ta buy
                        //if(pr>100)
                        //{
                        //    pr = 100;
                        //}
                        var predect = db.Database.ExecuteSqlCommand("UPDATE [product] SET predection = {0} WHERE productId={1}", q.predection=pr, q.productId);//predection ta daynamic
                        db.Product_Sells.Add(r); // ja sell hocche seta table e add hocche

                       
                       
                        var date = DateTime.Now.Date.Day;
                        var notnow = DateTime.Now;
                        var monthName1 = notnow.ToString("MMMM");
                        if (monthName1 == "January")
                        {

                            var status = db.Database.ExecuteSqlCommand("UPDATE [product] SET January = {0} WHERE productId={1}", q.January + 1, q.productId);
                            
                            
                            
                            var pred = (((q.January * 31) / date) + q.December + q.October + q.November) / 4;
                            var mod = (((q.January * 31) / date) + q.December + q.October + q.November) % 4;
                            pred = pred + mod;
                            var st = db.Database.ExecuteSqlCommand("UPDATE [product] SET PredectionResult = {0} WHERE productId={1}", q.PredectionResult = pred, q.productId);
                            db.SaveChanges();
                            if (q.PredectionResult > q.Buy)
                            {
                                var pre = q.PredectionResult;
                                var b = q.Buy;
                                var result = pre - b;
                                var status1 = db.Database.ExecuteSqlCommand("UPDATE [product] SET Result = {0} WHERE productId={1}", q.Result = result, q.productId);
                            }
                            //db.products.Add(q);
                            db.SaveChanges();

                        }
                        else if (monthName1 == "February")
                        {

                            var status1 = db.Database.ExecuteSqlCommand("UPDATE [product] SET February = {0} WHERE productId={1}", q.February + 1, q.productId);
                            
                           
                            var pred = (((q.February * 28) / date) + q.January + q.December + q.November) / 4;
                            var mod = (((q.February * 28) / date) + q.January + q.December + q.November) % 4;
                            pred = pred + mod;
                            var st = db.Database.ExecuteSqlCommand("UPDATE [product] SET PredectionResult = {0} WHERE productId={1}", q.PredectionResult = pred, q.productId);
                            db.SaveChanges();
                            if (q.PredectionResult > q.Buy)
                            {
                                var pre = q.PredectionResult;
                                var b = q.Buy;
                                var result = pre - b;
                                var status
                                    = db.Database.ExecuteSqlCommand("UPDATE [product] SET Result = {0} WHERE productId={1}", q.Result = result, q.productId);
                               
                            }
                            //db.products.Add(q);
                            db.SaveChanges();

                        }
                        else if (monthName1 == "March")
                        {

                            var status1 = db.Database.ExecuteSqlCommand("UPDATE [product] SET March = {0} WHERE productId={1}", q.March + 1, q.productId);
                           
                            
                            var pred = (q.February + q.January + q.December + ((q.March * 31) / date)) / 4;
                            var mod = (q.February + q.January + q.December + ((q.March * 31) / date)) % 4;
                            pred = pred + mod;
                            var st = db.Database.ExecuteSqlCommand("UPDATE [product] SET PredectionResult = {0} WHERE productId={1}", q.PredectionResult = pred, q.productId);
                            db.SaveChanges();
                            if (q.PredectionResult > q.Buy)
                            {
                                var pre = q.PredectionResult;
                                var b = q.Buy;
                                var result = pre - b;
                                var status = db.Database.ExecuteSqlCommand("UPDATE [product] SET Result = {0} WHERE productId={1}", q.Result = result, q.productId);
                                 }

                            //db.products.Add(q);
                            db.SaveChanges();

                        }
                        else if (monthName1 == "April")
                        {
                            var status1 = db.Database.ExecuteSqlCommand("UPDATE [product] SET April = {0} WHERE productId={1}", q.April + 1, q.productId);
                           
                            var pred = (q.February + q.January + ((q.April * 30) / date) + q.March) / 4;
                            var mod = (q.February + q.January + ((q.April * 30) / date) + q.March) % 4;
                            pred = pred + mod;
                            var st = db.Database.ExecuteSqlCommand("UPDATE [product] SET PredectionResult = {0} WHERE productId={1}", q.PredectionResult = pred, q.productId);
                            db.SaveChanges();
                            if (q.PredectionResult > q.Buy)
                            {
                                var pre = q.PredectionResult;
                                var b = q.Buy;
                                var result = pre - b;
                                var status = db.Database.ExecuteSqlCommand("UPDATE [product] SET Result = {0} WHERE productId={1}", q.Result = result, q.productId);
                               
                            }
                            //db.products.Add(q);
                            db.SaveChanges();


                        }
                        else if (monthName1 == "May")
                        {

                            var status1 = db.Database.ExecuteSqlCommand("UPDATE [product] SET May = {0} WHERE productId={1}", q.May + 1, q.productId);
                           
                           
                            var pred = (q.February + ((q.May * 31) / date) + q.April + q.March) / 4;
                            var mod = (q.February + ((q.May * 31) / date) + q.April + q.March) % 4;
                            pred = pred + mod;
                            var st = db.Database.ExecuteSqlCommand("UPDATE [product] SET PredectionResult = {0} WHERE productId={1}", q.PredectionResult = pred, q.productId);
                            db.SaveChanges();
                            if (q.PredectionResult > q.Buy)
                            {
                                var pre = q.PredectionResult;
                                var b = q.Buy;
                                var result = pre - b;
                                var status = db.Database.ExecuteSqlCommand("UPDATE [product] SET Result = {0} WHERE productId={1}", q.Result = result, q.productId);
                            }

Views/productsDetails/BuyProduct.cshtml
@model Project_497.Models.product

@{
    ViewBag.Title = "Shopping Cart";
    Layout = "~/Views/Layout/LayoutPage.cshtml";
    //if (Session["UserId"] == null)
    //{
    //    Response.Redirect("~/Login/Index");
    //}
}

<div>
     
                @* AFTER BUY A PRODUCT THEN THAT PAGE WILL BE SHOWN *@

    <hr />
    <dl class="dl-horizontal">
      


            <dd>
                <a href="#"><img src="@Url.Content("~/Multimidea/image/" + Model.image)" class="img-responsive img-thumbnail" style="width:450px;height:450px" /></a>
            </dd>
        <div style="padding:20px"></div>
            <dt class="text-center text-success" style="font-weight:900">
                @Html.DisplayNameFor(model => model.productName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.productName)
            </dd>
            <dt class="text-center text-success" style="font-weight:900">
                @Html.DisplayNameFor(model => model.price)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.price)
            </dd>
            @*<dt>
                @Html.DisplayNameFor(model => model.sellEndDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.sellEndDate)
            </dd>*@
       
    </dl>

        
    @*<h2 class="text-center text-primary">
        Want To Add More Product Into The Cart???
    </h2>
    <h3 class="text-center">Click Bellow</h3>*@

</div>


Views/productsDetails/DailySell.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Project_497.Models.Product_Sell>
@{ 
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}
<div style="padding:50px"></div>
<div class="navbar-static" role="navigation">

    @using (Html.BeginForm("Search_for_Daily_sell", "Product", FormMethod.Get))
    {
        <div>
            <input type="text" name="q"/>&nbsp;
            <input type="submit" value="Search" id="btnSubmit" class="btn btn-primary" /><span></span>
        </div>
    }

</div>
    <table class="custome-div table table-bordered table-condensed table-responsive table-hover table-striped" style="background-color:rgb(123,209,209)">

    <tr>

        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.First().productName)
        </th>

        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.First().price)
        </th>

        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.First().sellEndDate)
        </th>
       
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td class="text-center">
                @Html.DisplayFor(modelItem => item.productName)
            </td>

            <td class="text-center">
                @Html.DisplayFor(modelItem => item.price)
            </td>

            <td class="text-center">

                @Html.DisplayFor(modelItem => item.sellEndDate)
            </td>

        </tr>
    }

</table>

<div class="=Div-Pagination" style="padding:80px">

    @Html.PagedListPager(Model, page=>Url.Action("DailySell",new { page = page }))

    </div>

Views/productsDetails/Details.cshtml
@model Project_497.Models.product


@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/LayoutPage.cshtml";
}
<div style="padding:40px"></div>

<h2>Details</h2>
@*<p>@Html.ActionLink("<<Back", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })</p>*@

<div>

    @*<hr />*@
    <dl class="dl-horizontal">
        
           


                @if (Model.Buy > 0)
                {

                    
            <dd>
                <img src='@Url.Content("~/Multimidea/image/"+Model.image)'class="img-responsive img-thumbnail" style="width:400px;height:400px" />
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.productName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.productName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.price)
            </dd>



            <dd>
                <a href="#"><img src='@Url.Content("~/Multimidea/image/" + Model.offerImage)' class="img-responsive img-thumbnail"  /></a>
            </dd>

            <dd class="text-primary">
                @Html.DisplayFor(model => model.offerDetails)
            </dd>

            <dt class="text-primary ">
                @Html.DisplayNameFor(model => model.Buy)
            </dt>
            <dd class="text-danger">
                @Html.DisplayFor(model => model.Buy)
            </dd>
           
     }
                else
                {
                    <dd>
                        <img src='@Url.Content("~/Multimidea/image/"+Model.image)'class="img-responsive img-thumbnail" style="width:400px;height:400px" />
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.productName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.productName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.price)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.price)
                    </dd>

                    <dd>
                        <a href="#"><img src='@Url.Content("~/Multimidea/image/" + Model.offerImage)' class="img-responsive img-thumbnail" /></a>
                    </dd>

                    <dd class="text-primary">
                        @Html.DisplayFor(model => model.offerDetails)
                    </dd>

                    <dt class="text-primary ">
                        @Html.DisplayNameFor(model => model.Buy)
                    </dt>
                    <dd class="text-danger">
                        <p>SOULD OUT</p>
                    </dd>
                }
               

                <dt>
                    <a href="@Url.Action("BuyProduct", "productsDetails", new { id=Model.productId}) ">
                        <input id="Button1" type="button" value="BUY NOW" class="btn btn-success btn-xs btn-sm" />
                    </a>
                </dt>
            </dl>





        </div>


















        @*<dt>
                @Html.DisplayNameFor(model => model.offerDetails)
            </dt>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.sellStartDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.sellStartDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.sellEndDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.sellEndDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.isNew)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.isNew)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.click)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.click)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Admin.userName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Admin.userName)
            </dd>*@

Views/productsDetails/PurchaseSuggestionForAdmin.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Project_497.Models.product>
@{
    ViewBag.Title = "Purch Suggestion";
    Layout = "~/Views/Layout/LayoutPage.cshtml";
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}
<div style="padding:50px"></div>
<table class="custome-div table table-bordered table-condensed table-responsive table-hover table-striped" style="background-color:rgb(123,209,209)">

    <tr>
        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.First().productId)
        </th>
        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.First().productName)
        </th>

        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.First().price)
        </th>

        <th class="text-center text-success" style="font-weight:900">
            @Html.Label("Purches Suggestion")
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.productId)
            </td>

            <td class="text-center">
                @Html.DisplayFor(modelItem => item.productName)
            </td>

            <td class="text-center">
                @Html.DisplayFor(modelItem => item.price)
            </td>

            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Result)
            </td>


        </tr>
    }

</table>
<div class="=Div-Pagination" style="padding:80px">
    @Html.PagedListPager(Model, page => Url.Action("PurchaseSuggestionForAdmin", new { page = page }))
</div>

Views/productsDetails/Search.cshtml
@model IEnumerable<Project_497.Models.product>
@*@model Project_497.Models.product*@

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Layout/LayoutPage.cshtml";
}




                                                            @* THAT PAGE WILL SHOW AFTER YOU SEARCH FOR A PRODUCT  *@
<p style="font-size:larger; padding:10px; font-weight:900">

    @Html.ActionLink("Product", "Index", "Product")
</p>
<table class="custome-div table table-bordered table-condensed table-responsive table-hover table-striped" style="background-color:rgb(123,209,209)">

    <tr class="text-primary">
        <th class="text-center text-success" style="font-weight:900">

        </th>
        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.productName)
        </th>

        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.price)
        </th>


        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.category.name)
        </th>


        <th class="text-center text-success" style="font-weight:900"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="img-thumbnail img-responsive" style="width:200px; height:200px">
                <a href="@Url.Action("Details", "productsDetails", new { id=item.productId}) ">
                    <img src="@Url.Content("~/Multimidea/image/"+item.image)" class="btn-block img-responsive img-thumbnail" />
                </a>
            </td>
            <td class="text-center text-primary">
                @Html.DisplayFor(modelItem => item.productName)
            </td>

            <td class="text-center text-primary">
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td class="text-center text-primary">
                @Html.DisplayFor(modelItem => item.category.name)
            </td>


        </tr>
    }

</table>

Views/productsDetails/predections.cshtml
@model IEnumerable<Project_497.Models.product>
@{ 
    if (Session["UserId"] == null)
    {
        Response.Redirect("~/Login/Index");
    }
}
<div style="padding:50px"></div>
<table class="custome-div table table-bordered table-condensed table-responsive table-hover table-striped" style="background-color:rgb(123,209,209)">

    <tr>
        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.productId)
        </th>

        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.productName)
        </th>

      

        <th class="text-center text-success" style="font-weight:900">
            @Html.DisplayNameFor(model => model.predection)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.productId)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.productName)
            </td>
            

            <td class="text-center">
                @Html.DisplayFor(modelItem => item.predection)
            </td>

        </tr>
    }

</table>